### ISSUE TITLE
Feature request: do not suspend pinned tabs

### ISSUE THREAD

**Issue by Vinnl** [k5md/Total-Suspender-webextension#1]
The extension appears to work very well on first use, but one feature that I would appreciate is if it would not suspend my pinned tabs. The reason I keep those pinned is because I want to see what's new there, and that's not possible when they are suspended.

**Comment by k5md** [comment]
Hello! I thought that it's better to introduce this feature as an option, just like "ignore tabs producing sound", but now it seems that pinned tabs are not meant to be suspended or closed. Thank you, I'll merge the fix with master and release the new version.

**Comment by Vinnl** [comment]
That was quick, thanks! Looking forward to updating :)

Btw, speaking of options: there's also the [`options_ui` key in `manifest.json`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Options_pages). Not sure if it's a conscious choice to add a toolbar button just to access the options, but if not, using `options_ui` might be preferable, as it allows users to access the options through the add-ons manager.

**Comment by k5md** [comment]
> Not sure if it's a conscious choice to add a toolbar button just to access the options,

It is :) Thought, that it could be more intuitive for new users to have a button to quickly access the options. If the list will get huge I'll surely move advanced settings in the extension options and leave general in this section.
