### ISSUE TITLE
Question: what does the number represent?

### ISSUE THREAD

**Issue by businessBoris** [k5md/Total-Suspender-webextension#11]
It's usually one less than the total number of tabs (per Tab Tally); so it's the unloaded tabs number right?

Please could you change the number (background?) colour - back on grey isn't ideal.

Thank you.

BTW: although FF v67 has backgrounding ability. The criteria for unloading tabs are not very stringent. Your add-on is still very very helpful.

**Comment by k5md** [comment]
Hello, @businessBoris !
I've changed the colour.
As for the number - it's total tabs count. And the fact, that it has been one tab less than actual existing tabs count turned out to be another wonderful firefox feature. Hopefully, it'll display correct value now.
