### ISSUE TITLE
"Ignore pinned tabs" cannot be disabled

### ISSUE THREAD

**Issue by MCP1** [k5md/Total-Suspender-webextension#12]
It seems the option to disable discarding pinned tabs cannot be disabled, irrespective of the choice in "Ignore pinned tabs" in "Settings" tab. My pinned tabs are never discarded, even if I use the button "Suspend now if criteria match" the "Actions" tab. However, if I click in "Suspend all tabs now", all my pinned tabs are immediately discarded.

Thanks for the excellent extension!

**Comment by k5md** [comment]
Hello, @MCP1 !
Thank you for the feedback! Sadly, this bug was introduced in the current version while transitioning to mithril. I have confirmed the issue, will release the fix as soon as possible.

**Comment by MCP1** [comment]
Tks!

**Comment by k5md** [comment]
Fixed. I'll publish new version today including this fix and fix for imports bug. Thank you for noticing it!

**Comment by MCP1** [comment]
Thanks @k5md. Working perfectly now. Pinned tabs being closed by the timer and the button when ignore pinned option is disabled.
