### ISSUE TITLE
Suspend the oldest used tab first.

### ISSUE THREAD

**Issue by LichenSymbiont** [k5md/Total-Suspender-webextension#14]
There's got to be a list for it, as FF has tab switching ordered by access-time (ctrl+tab).

Or the list could be created by OnActivated, popping the tab to the list.

**Comment by k5md** [comment]
Hello, @LichenSymbiont !
This is an awesome feature suggestion! Yes, FF tabs have lastAccessed property, so it would be easy to sort discardable tabs on access time. I'll implement this feature in the next release. Thank you!

**Comment by LichenSymbiont** [comment]
Awesome! :)
