### ISSUE TITLE
ADD ability to suspend currently active tab

### ISSUE THREAD

**Issue by allanlaal** [k5md/Total-Suspender-webextension#18]
I heard a rumour somwhere that Firefox's native suspend mechanism does not the availability to suspend the currently active tab, but maybe you could build sth on top of it to lessen the CPU/RAM cost of each active tab destined for suspend :)

**Comment by k5md** [comment]
Hello, @allanlaal !
Sorry for the late reply. Yes, Firefox does not allow one to suspend active tabs. By suspending I mean native Firefox feature that unloads not active tab from memory and stores it in cache. Active tabs are those, that are currently seen by a user, it's one active tab per browser window. So, it is logical that active tabs can not be suspended.

**Comment by allanlaal** [comment]
I am aware of the native Firefox suspension limits and there are tickets currently open on Bugzilla about the same thing

The Great Suspender on Chrome made a greyed out screenshot of the webpage and replaced that inside the tab. only when you clicked the massive Refresh button in the center of that image, would it reload the tab (with forms filled as much as they were before "suspending")

can you make a similar feature?
