### ISSUE TITLE
Time limit until tab suspends? 

### ISSUE THREAD

**Issue by MattyTheDev** [k5md/Total-Suspender-webextension#19]
Hi there, when working with multiple tabs, i find the other tab I need is suspended straight away. 

Is there some way I can keep it live for say 5 minutes for example? Is that an option I can choose and if so, where is it? 
Or is this something that would need to be programmed in? 

Warmly
Matt

**Comment by k5md** [comment]
Hello, @curiousMatt !
Yes, there is an option for this in settings (click on the popup icon), it's labeled 'Suspend after this many seconds'. Suspension is delayed by 1 minute by default.

**Comment by MattyTheDev** [comment]
Ok yay.

Thanks so much for your help. I knew you would've made it easy. Sorry for
your time.
