### ISSUE TITLE
Wording: negative question on control panel "Disable suspension"

### ISSUE THREAD

**Issue by businessBoris** [k5md/Total-Suspender-webextension#3]
I'm not wanting to be "that guy". I just don't find it easy to understand.
What does "Disable suspension [is] off" mean? Could we have something like "Suspension: off" instead?

Negative questions in English don't work very well usually.

OT: is there a place in Firefox where one can see the number of loaded tabs?

**Comment by k5md** [comment]
Hello!
Sorry for the late reply and thanks for correction, I'll fix it in the next release.

> OT: is there a place in Firefox where one can see the number of loaded tabs?

This feature is not implemented in the current version, you want tab counter to be a badge text like in Adblock Plus or should it better be on addon popup, among settings and other?

**Comment by businessBoris** [comment]
Thank you very much for changing that. I got myself confused trying to workout whether it was working on my machine (no clashes with other add-ons etc)!

I use "tab tally" to show the number of loaded tabs in the hover-tip - I think it's the only one that does show the loaded count - but I'm not sure it gets updated over time.

Some kind of indication that your add-on is doing its stuff would be helpful for me; briefly changing the colour of the icon or something!

Thank you again.

**Comment by k5md** [comment]
You are welcome! These suggestions help me make the extension better, so it's always great to get feedback from users.
As for the loaded tabs indication, it seems to be a nice feature to add, I'll implement this in a couple of days.

**Comment by businessBoris** [comment]
I'm liking the updates! Great stuff.
