### ISSUE TITLE
Option to have a "Blacklist" mode. Only suspend websites that are in Blacklist.

### ISSUE THREAD

**Issue by smartfonreddit** [k5md/Total-Suspender-webextension#4]
Hi. Thanks for the addon!

There is an option to whitelist a URL. Is it possible to have the opposite, too? I only want to suspend YouTube tabs, and leave all other websites alone.

For example, 

`https://www.youtube.com` is in the Blacklist. All YouTube tabs, and **only** YouTube tabs, will be suspended. However...

having `https://www.youtube.com/playlist?list=WL` (the Watch Later playlist URL) in the Whitelist would overwrite the Blacklist. That means all YouTube tabs, except for the Watch Later URL, would be suspended.

**Comment by k5md** [comment]
Hello! Yes, it's possible and easy to implement with the current extension architecture, I'll implement this in the next release together with tabs stats. Thanks for proposing this functionality.

**Comment by smartfonreddit** [comment]
Hello,
The addon just updated. It appears to be partially broken. I have the tab suspension initiation threshold set at 10. Suspension is every 5 seconds. There are currently more than 10 open tabs.

There are:
1. A few YouTube videos
2. YouTube Watch Later Playlist `https://www.youtube.com/playlist?list=WL`
3. Few Reddit tabs.

Whitelist and Blacklist are ON. Under Whitelist I have `https://www.youtube.com/playlist?list=WL`.
Under Blacklist I have `https://www.youtube.com/`

The expected result is that none of the Reddit tabs or the Watch Later playlist should be suspended. Only the YouTube videos should suspend. 
It appears that the Watch Later (in Whitelist) does suspend but well after the 5 seconds configured in settings, and Reddit tabs also suspend even though they aren't in Blacklist.

**Comment by smartfonreddit** [comment]
It appears the patch has worked. Thanks. This is now the most powerful tab suspender addon!
