### ISSUE TITLE
Option to suspend tabs only if more than X number of tabs are open.

### ISSUE THREAD

**Issue by smartfonreddit** [k5md/Total-Suspender-webextension#5]
Hello again,

Would it be possible to activate the suspension only if more than X number of tabs are open? Having fewer than X tabs never causes RAM or CPU problems, so it's not necessary to suspend. Suspending tabs comes with the annoyance of having to wait for the whole tab to reload. We can avoid this if the tab didn't have to be suspended to begin with.

**Comment by k5md** [comment]
Well, I had the idea of having no more than N loaded tabs and even implemented this in one of the earlier versions, but it didn't seem clear (at least, to me), how users would understand this functionality, your idea of setting a threshold for tabs count seems much more understandable, same as previous request - will include in the next release.
