### ISSUE TITLE
"Suspend when tab count reach" - description could be clearer

### ISSUE THREAD

**Issue by ReporterX** [k5md/Total-Suspender-webextension#7]
The option "Suspend when tab count reach" is not that clear in two ways.

First, I wonder if it means the total number of tabs I have, or the number of **loaded (active)** tabs I have. I did a test, so it appears it actually means active tabs.

Second, according to the text, the auto-suspend should kick in once the number is reached (i.e. equal to the number).  
For example if I type 5, I expect auto-suspend will start if I have 5 loaded tabs.  
However it actually starts if I have 6.  

In my humble opinion, I think it will be much clearer if the description is written as:  
"Suspend when the number of loaded tab is higher than", or  
"Suspend when the number of active tab is higher than"

Thank you.

**Comment by k5md** [comment]
> First, I wonder if it means the total number of tabs I have, or the number of loaded (active) tabs I have. I did a test, so it appears it actually means active tabs.

It means tabs, that are not active, not pinned and not discarded, I agree, it's not clear, but including such a long description could make it even more unclear. I'm going to put ignoring pinned tabs into a separate options entry, so your suggested description will fit nice.
I'll include the fix in the next release.

**Comment by ReporterX** [comment]
I see, so the selected tab does not count. You may change it this way: 

Suspend when the number of loaded tab(s) reaches ____
 - [ ] Count the selected tab(s)
 - [ ] Count pinned tab(s)

The word "selected" is better than "active" IMHO. Some users do not know what active tabs mean. They may interpret it as "loaded tabs".

**Comment by aashish108** [comment]
I still do not understand. What happens if I have greater than 5 tabs and if the field "Suspend when tab count reach" has 1 in it and I have 60 in suspend after this many seconds and 60 seconds have passed - what will happen?

**Comment by k5md** [comment]
If we do not take into consideration other settings and you didn't perform any actions (e.g. open new tab, attach or detach it, change settings) in this time, after 60 seconds have passed, loaded tabs will be discarded, except for the currently active ones.

**Comment by businessBoris** [comment]
I can't actually see any digits in the space left for a number. 
Am I alone?
[ Agree with other posts in the thread about description clarity ]
