### ISSUE TITLE
Question about matching patterns in whitelist/blacklist mode

### ISSUE THREAD

**Issue by ReporterX** [k5md/Total-Suspender-webextension#9]
1. What happens if I put `example.com` in the list? Does it work in all three cases?
A. example.com
B. www.example.com
C. sub.example.com

2. Does it support `*` or `?` wildcard, or regex syntax?

3. If I want to export/import a long list of domains, how?

Thank you.

**Comment by k5md** [comment]
1. Yes, the extension will simply check if tab's URL contains 'example.com' substring, so it's supposed to work in all three cases.
2. No. I've thought of adding regex support, it poses no difficulty, but I thought, that it may be to complicated for some users and usecases are not clear.
3. Currently there is no way to do it from the UI. Well, if you are asking for a workaround, one can open extension debug window in about:debugging and explicitly save list of domains to storage or load from it. I didn't think that there were actually any suspending extensions that support white- and blacklisting, so, I guessed there were no actual lists to import. I can add this feature in one of next versions.

**Comment by ReporterX** [comment]
Wildcard is a good choice since average Joe can use it. Regex offers more flexibility but is harder to use. I know Regex and I'm a power user.

Please add regex support (or wildcard, up to you). You may simply add "Regex is supported" at the end of the statement (description). They will use for those who know. Otherwise it can be simply ignored. There are several benefits:
1. Let say you want to whitelist/blacklist all Google domains, for example `google.com`, `google.co.in`, `google.co.uk` and so on. You can add them all in one line. Currently you have to manually add one by one.
2. I can put all relevant/subsidiary websites in one line (acting like a group).

**Comment by k5md** [comment]
I surely will implement this.

**Comment by k5md** [comment]
Hello!
Sorry, that it took so long, I've been rewriting the extension to support more complex UI, localizations and chrome support. In the version that I've just released whitelists and blacklists support regular expressions.
